### ISSUE TITLE
Determine Best Hosting Solution

### ISSUE THREAD

**Issue by MykalMachon** [ufvcsa/ufvcsa.github.io#19]
See #12 for additional context on this issue

## Summary of Issue
We need to configure github pages hosting for the repo. 

This may involve creating a CI/CD server like [Travis CI](https://enterprise.travis-ci.com/) or [Circle CI](https://circleci.com/) to rebuild and redeploy the site upon commits to the repo. 

A good starting point would be [this tutorial on Gatsby's Docsite ](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/#deploying-to-github-pages-from-a-ci-server)

@MJJBennett has already started work on this in #18

**Comment by MJJBennett** [comment]
It's looking like it won't be possible to do this through `/docs` unfortunately:

![image](https://user-images.githubusercontent.com/33364401/66161332-e9d50e80-e5e0-11e9-9883-2d48066f4a00.png)

**Comment by MykalMachon** [comment]
Ah, well.
That kind of ruins the whole GitHub Pages use case doesn't it 😞 

We'll have to figure out a better way to host the site as having the build files mixed in with the source files is a super bad practice (no build automation, etc)

**Comment by MykalMachon** [comment]
Update: @MJJBennett got some server space for us on the UFV server! 🎉 🎈 

Currently the site is manually deployed but we will be looking into automation options (i.e build and redeploy on push to master) if we determine they're needed. 

Thanks again @MJJBennett , I'll be closing this issue for now as we have got some hosting setup!
