### ISSUE TITLE
Analyze / Fix Gatsby build problems

### ISSUE THREAD

**Issue by MJJBennett** [ufvcsa/ufvcsa.github.io#30]
After #29 merged it appears that some of the new React additions (for responsive web design) don't play well currently with a static Gatsby build. It's not currently necessary to only build statically, so the main two approaches to fix this are either to fix the issue with regards to how Gatsby would suggest (https://www.gatsbyjs.org/docs/debugging-html-builds/) or to see if there's a non-static way to do this, but that might not be worthwhile.

This is the error when running `gatsby build`:

```
failed Building static HTML for pages - 1.712s

 ERROR #95312

"window" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


   5 |   constructor(props) {
   6 |     super(props);
>  7 |     this.state = window.innerWidth < 1024 ? { showNav: false } : { showNav: true };
     |                  ^
   8 |     this.toggleNav = this.toggleNav.bind(this);
   9 |   }
  10 |


  WebpackError: ReferenceError: window is not defined

  - header.js:7 new Header
    src/components/header.js:7:18
```

@MykalMachon any suggestions? I think this should be a fairly easy fix to get this working right now, but for the future is there a specific approach that should be taken for design?

**Comment by MykalMachon** [comment]
Whoops! the line using `window` to determine screen size slipped past me!

There is a super easy way we can pull out some of this javascript state management with good old CSS. To avoid this in the future there are a few things we should probably do: 

1. Encourage developers & ourselves to try and build the site before merge & to validate that personally before merge.
2. Avoid the use of any browser builtins as much as possible (`window` being one) as when gatsby builds a site (creates static HTML pages from react & content) it does so without access to these builtins. 
3. If you have to use a browser builtin like `window.innerWidth` make sure to check if `window` exists first. This way, when gatsby is building the static HTML page and doesn't have access to `window` it won't cause an error, but when a user opens the page in chrome and they do have access to `window,` everything will work as expected. 
```js
if(window){
  // do stuff with window here
}
```

**Comment by CalebLangbroek** [comment]
Ahh, I also missed that. Good to note for next time. I would suggest using the `componentDidMount()` function though. Right now, the current solution is causing issue #32 because the window is undefined, so on the initial load the navbar is set to show.
